/*   Do *not* directly modify this file.  It was    */
/*   generated by the Configuration Tool; any  */
/*   changes risk being overwritten.                */

/* INPUT finalp.cdb */

/*  Include Header File  */
#include "finalpcfg.h"

/*  Config Structures */
/*  Handles  */
