

/* This file contains the PRU instructions in a C array which are to  */
/* be downloaded from the host CPU to the PRU instruction memory.     */
/* This file is generated by the PRU assembler.                       */



unsigned int PRUCode[] =  
{
    0x24000080,
    0x240000c0,
    0x2400009f,
    0x240000df,
    0x24000281,
    0x240000c1,
    0x81342081,
    0x24080080,
    0x01028080,
    0x24000281,
    0x80800001,
    0x24040080,
    0x0120e0e0,
    0x24000201,
    0x80800001,
    0x24002081,
    0x240000c1,
    0x81242081,
    0x81282081,
    0x24000181,
    0x81100081,
    0x24002081,
    0x240000c1,
    0x24740080,
    0x248000c0,
    0x2476108a,
    0x248000ca,
    0x2429c089,
    0x248000c9,
    0x24000082,
    0x24c3f0c2,
    0x24016083,
    0x24c3f0c3,
    0x2402c08b,
    0x24c3f0cb,
    0x2404208c,
    0x24c3f0cc,
    0x240000c4,
    0x3e000000,
    0x10000000,
    0x24000084,
    0x2400008d,
    0x240000cd,
    0x2400008e,
    0x01028484,
    0x6fb084fc,
    0x0102c4c4,
    0x6f90c4f9,
    0x2400209f,
    0x240000df,
    0x81242081,
    0x21001700
};

